<div class="page-header" xmlns="http://www.w3.org/1999/html">
    <a class="btn btn-sm btn-primary pull-right"
       href="<?php echo $this->url('sistema', array('action' => 'adicionar')); ?>">
        <span class="glyphicon glyphicon-plus"></span>
        Adicionar
    </a>
    <h3>Manter Sistema</h3>




</div>

<div ng-controller="SistemaController">
    <div class="input-group col-sm-12 col-md-12">
        <form name="pesquisaForm" novalidate >
            <div id = "alert_placeholder"></div>

            <div class="alert alert-danger"id="emailinvalido" ng-show="pesquisaForm.searchEmail.$error.pattern" >
                <a class="close" data-dismiss="alert">×</a><span>
                E-mail inválido.
            </div>
            <label>Descricao</label><input type="text" class="form-control input-sm" maxlength="100" ng-model="searchText"
                   placeholder="Descriçao" type="search"   />
            <br>
            <label>Sigla</label><input type="text" maxlength="10"class="form-control input-sm" ng-model="searchSigla"
                                           placeholder="Sigla" type="search"  />
            <br>
            <label>E-mail</label><input type="text" name="searchEmail" maxlength="100" class="form-control input-sm" ng-model="searchEmail"
                                       placeholder="E-MAIL" type="search"
                                        ng-pattern="/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/" />



            <br><br><br><br>

                <button  ng-disabled="pesquisaForm.$invalid" ng-click="search()"><span class="glyphicon glyphicon-search" ">Pesquisar</span></button>
            <button ng-click="limpar()" type="reset"><span class="glyphicon glyphicon-trash" ">Limpar</span></button>

    </div>
    <table  id="resultados" ng-if="paginator._embedded.api_sistema_" class="table table-striped table-condensed">
        <thead>
        <tr>
            <th>
                Descrição
            </th>
            <th>
                Sigla
            </th>
            <th>
                E-mail
            </th>
            <th>
                Ações
            </th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="sistema in paginator._embedded.api_sistema_">
            <td>
                {{sistema.descricao}}
                
            </td>
            <td>
                {{sistema.sigla}}

            </td>
            <td>
                {{sistema.email}}
            </td>
            <td>
                <a href="<?php
                echo $this->url('sistema', array(
                    'action' => 'editar'
                ));

                ?>/{{sistema.id}}">
                    <span class="glyphicon glyphicon-pencil"></span>
                    Editar
                </a>
            </td>
        </tr>
        </tbody>
    </table>
    <ul class="pagination" id="paginador">
        <li ng-if="paginator._links.prev && paginator.page_count > 1">
            <a href="#"
               ng-click="navigate(paginator._links.prev.href)">
                &lt;&lt;
            </a>
        </li>
        <li ng-if="paginator._links.first && paginator.page_count > 1">
            <a href="#"
               ng-click="navigate(paginator._links.first.href)">
                Primeiro
            </a>
        </li>

        <li

            ng-repeat="i in getNumber(paginator.page_count) track by $index"
            ng-if="paginator.page_count > 1 &&   $index < 10"
            ng-attr-class="{{paginator.pageActive == $index + 1 && 'active'}}"
        >
            <a
                ng-click="navigate(paginator._links.first.href, ($index + 1))"
                href="#"
            >{{$index + 1}}

            </a>

        </li>

        <li ng-if="paginator._links.last && paginator.page_count > 1">
            <a href="#"
               ng-click="navigate(paginator._links.last.href)">
                Último
            </a>
        </li>
        <li ng-if="paginator._links.next">
            <a href="#"
               ng-click="navigate(paginator._links.next.href)" >
                &gt;&gt;
            </a>
        </li>
    </ul>
    </form>
</div>