<div class="jumbotron">
    <h1> <span class="zf-green">Manter Sistema</span></h1>

    <p>
     Caso de uso manter sistema
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/jairjunior28/TesteSquadra" target="_blank">Código no GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"></h3>
            </div>
            <div class="panel-body">
                <p>

                </p>

                <p></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"></h3>
            </div>
            <div class="panel-body">
                <p>
                </p>

                <p></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"></h3>
            </div>
            <div class="panel-body">
                <p>
                </p>

                <p></p>
            </div>
        </div>
    </div>
</div>
